### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by aldodemi** [MarlBurroW/google-home-notification-center#11]
web interface work but when I use the http get request I receive this error (on two debian linux machine) 
Error: get key failed from google
    at /home/aldo/google-home-notification-gateway/node_modules/google-tts-api/lib/key.js:27:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

curl: (52) Empty reply from server

**Comment by aldodemi** [comment]
curl: (52) Empty reply from server
